### ISSUE TITLE
Bug in Filter Fields

### ISSUE THREAD

**Issue by tkaraoglu** [aruba/pyclearpass#3]
https://github.com/aruba/pyclearpass/blob/12d2b332dff5bda52b3ab166ad8aa182bc372fd7/pyclearpass/common.py#L175

In Clearpass filters expected value for filters by the server is a JSON filter like `{"username": "blabla@gmail.com"} ` however _generate_parameterised_url function just returns a regular encoded url format `username=blabla@gmail.com` which results in 422 error code for any search point requiring a filter expression. Correct expression should be as follows: 

```
import json
from urllib.parse import quote

print(quote(json.dumps({"username": "blabla@gmail.com"})))
```

**Comment by sjtarik** [comment]
Proposing solution here in this PR #4

**Comment by jazzyj123** [comment]
Hi All. Thanks for reaching out. This is on my radar and will be fixed in the coming days and also uploaded to the Pypi repository.

**Comment by jazzyj123** [comment]
Hi @sjtarik & @tkaraoglu. Thank you for the support with this issue. The issue was related to the way the _generate_parameterised_url method in the common.py file handles the filters associated with Python dict objects. It will now check for the dict object and convert correctly to JSON before encoding the URL. Thank you once again for bringing this to our attention and I hope this solves your issue and you continue to enjoy using pyclearpass.   

P.S - you can upgrade pyclearpass using 'pip install pyclearpass --upgrade' without the single quotes.

**Comment by sjtarik** [comment]
@jazzyj123  thank you so much for quickly addressing the issue. I might send another PR for adding an "how to filter users?" part to the README file later.

**Comment by jazzyj123** [comment]
@sjtarik - just for reference, the filters are described in the below link but I agree we are missing content from the readme which describes their usage.  I can take some of the content in the link and include it in the next update.  I will also update the devhub website after the next ClearPass update. Thanks for raising this, it is really appreciated.  https://www.arubanetworks.com/techdocs/ClearPass/6.12/Guest/Content/AdministrationTasks1/API_Filtering.htm
